// Essay body content. Kept separate from essays.ts metadata so the index
// page renders fast without loading every body.

export const essayBodies: Record<string, { paragraphs: string[]; headings?: Record<number, string> }> = {
  "why-most-smb-ai-pilots-die": {
    paragraphs: [
      "Three patterns account for ~80% of SMB AI failures, and they all look the same in month four. The pilot was exciting in month one. The model worked in month two. Adoption stalled in month three. By month four the executive sponsor is quiet and the project becomes one of those things people stop asking about.",
      "Pattern one is pilot purgatory. One enthusiastic VP runs a 90-day experiment. The model works on her use case. There's no governance, no measurement framework, no champion network — and crucially, no plan to scale beyond the VP's own team. When the pilot ends, the org returns to status quo. The VP gets credit for the pilot in her review; the company doesn't ship anything.",
      "Pattern two is the compliance freeze. Legal and security block AI use until 'policy is ready.' Policy is never ready, because the compliance team has never seen a defensible AI deployment template and defaults to no. The org's enthusiasm decays. By month six the executives are reading about competitors deploying AI in trade press while their own compliance review is still pending.",
      "Pattern three is the Big-4 quote. The company decides AI is strategic, calls in Deloitte or Accenture, gets a $200k–$2M strategy engagement, receives a deck and a roadmap and exactly zero deployed workflows. Senior partners sell; analysts deliver. The SMB economics never close because the pyramid model isn't built for sub-enterprise budgets.",
      "What works at the SMB tier is the same thing that works at the enterprise tier — but priced and scoped for organizations between 10 and 250 employees. Senior judgment, productized engagements, measurable adoption, structured partner relationships. That's the practice this site documents.",
      "The mistake I see most often is treating AI deployment as a tooling problem. It isn't. It's a change management problem with an unusually capable tool in the mix. The orgs that ship are the orgs that take change management seriously — governance before tools, champions over training, use-case ladders over feature dumps, measurement from day one, senior judgment on call. The orgs that stall are the orgs that bought a license and assumed adoption would happen.",
      "If you're somewhere on this curve and want to do a structured five-pillar self-check, the readiness tool at /hr/tools/readiness will surface where you are in about five minutes. If you want the full assessment, the 7-Day Audit does the interview-based version with a written roadmap. Either way, the answer is rarely the model — it's the deployment.",
    ],
  },
  "five-pillar-adoption": {
    paragraphs: [
      "The framework that's worked across very different organizations has the same five pillars in the same order. The order is load-bearing — getting it wrong is usually how programs die.",
      "Pillar one: governance before tools. The most common mistake is to buy a license and then draft a policy. That sequence guarantees six months of back-and-forth between IT, legal, and compliance, during which everyone's enthusiasm decays. The right sequence is the reverse. Draft the policy first, in collaboration with compliance, with the use cases informing the policy and the policy informing the vendor evaluation. The compliance team becomes co-author of the rollout instead of gatekeeper.",
      "Pillar two: champion network, not training. Traditional top-down training has 15–25% adoption rates. A cross-functional champion cohort of 15–25 people, trained in cohort-format with ongoing access to leadership and to each other, translates AI for their teams in their teams' language. That's worth 5–10× more than top-down training, and the math compounds because the champions also become the first responders for adoption issues in their departments.",
      "Pillar three: use-case ladder. When you give a workforce general-purpose access to an LLM, the typical response is paralysis. The tool can do anything; therefore staff use it for nothing. The pattern that works is laddering — start with three high-ROI low-risk use cases per department, sequence the rollout, document the wins, then add the next layer. Boring use cases (drafting, summarizing, formatting) produce most of the early wins.",
      "Pillar four: measurement from day one. Most organizations report 'AI adoption' as license utilization, which is meaningless — logging in once a month is not adoption. Real adoption is weekly active users producing artifacts, with time-savings sampled (not estimated) and error rates flagged. Without measurement, the program can't be defended in the next budget cycle. With measurement, it gets defended automatically because the numbers do the work.",
      "Pillar five: senior judgment on call. Every program needs a decision-maker reachable for edge cases on a same-day cadence. 'Can I use this for patient communication?' 'What about this vendor we want to try?' 'How do I respond to this employee complaint about AI use?' When those questions have no answer, the program freezes. When they have an answer in 24 hours, the program ships.",
      "In a 50-person tech startup, the five pillars look light: governance is a one-page Notion doc; champions are 5–6 mid-level operators; the use-case ladder is two department-specific deployments; measurement is a Mixpanel dashboard; senior judgment is the founder. In a 250-person FQHC, the pillars look heavier: governance is reviewed by external HIPAA counsel; champions are 22 staff across every clinic and back-office team; the use-case ladder includes patient-facing work that gates on compliance; measurement is a real dashboard with quarterly board reporting; senior judgment is a director-level operator with clinical-team trust. Same framework, different weight.",
      "The pillars work as a sequence, not a checklist. Stage one (Diagnose) maps the org against the pillars. Stage two (Design) drafts governance, selects vendors, identifies champions. Stage three (Deploy) trains champions and ships pilot use cases. Stage four (Measure) instruments adoption. Stage five (Scale) adds the next layer of use cases. Each stage gates on the previous one — skipping ahead is the most common failure mode in self-serve attempts.",
    ],
  },
  "compliance-without-the-freeze": {
    paragraphs: [
      "The single most common reason AI deployments stall in regulated environments isn't the model, the data, or the use case. It's the compliance team — and the compliance team isn't wrong. They've never seen a defensible deployment template, so they default to no.",
      "The pattern that works is to make compliance a co-author of the rollout, not a gatekeeper. That sounds small. It isn't. It changes the entire emotional shape of the project. Co-authors say 'here's how we'd do that.' Gatekeepers say 'we can't approve that.' The deployment work is identical; the political work is opposite.",
      "Concretely: in week one of an engagement with a healthcare organization, the first stakeholder interview is with the compliance officer. Not the CEO, not the CTO — the compliance officer. The goal is twofold: surface the constraints she's actually worried about (which are usually narrower than the rest of the org assumes), and earn her partnership in drafting the policy that addresses those constraints.",
      "The policy itself follows a tight format. Acceptable-use clauses tied to data classifications. Vendor evaluation criteria including BAA quality and data-handling provisions. Specific prohibited uses (almost always shorter than people expect). An incident response protocol. An annual review schedule. Approximately 8–12 pages including appendices. Reviewed by external counsel where the risk warrants it.",
      "The vendor evaluation runs in parallel. Three or four shortlisted vendors get put through the same checklist — data residency, training-data usage, BAA terms, retention policies, incident escalation paths. The compliance officer sees the comparison matrix before any contract is signed. By the time the contract is in front of legal, every blocking question has already been answered. The legal review takes two weeks instead of two months.",
      "The hardest part isn't the technical work — it's the relationship work. The compliance officer has to believe you respect her job. The way you demonstrate that is by knowing more about her regulatory environment than she expects, by showing up with the template she'd have drafted if she had time, and by giving her credit publicly when the deployment goes well. Compliance officers who feel respected accelerate programs. Compliance officers who feel bypassed kill them.",
      "The 83% adoption case study was made possible by this sequence. The compliance officer signed off on the governance framework in week three. By week six the first use case was in production. By month nine adoption was at 83%. None of that happens if compliance is told to 'wait' or 'get out of the way.'",
    ],
  },
  "measuring-adoption-honestly": {
    paragraphs: [
      "Most organizations report AI adoption as license utilization. 'We have 200 seats, 180 have been activated, we're at 90% adoption.' This is the metric you report when you don't want to know the answer.",
      "Activation isn't usage. Logging in once isn't usage. Weekly active users producing artifacts is usage. The first thing every honest measurement framework does is throw out license-utilization as a metric and replace it with WAU.",
      "The full instrumentation that works: weekly active users (defined as users who completed at least one productive interaction in the trailing 7 days); prompts per user per week (separates the 'logged in but never used it again' cohort from the active cohort); use-case attribution (which use cases drive most usage); error-flag rate (the % of interactions where the user flagged an output as problematic — this is your quality signal); time-savings sampled, not estimated (every quarter, ask 20 users to log a representative day's AI usage and self-report estimated time savings — extrapolate carefully).",
      "License utilization can stay in the dashboard, but as a leading indicator only. The lagging indicator is WAU. The quality indicator is error-flag rate. The ROI indicator is sampled time-savings. Three numbers, three signals, that's the dashboard.",
      "The board version of the dashboard is even simpler. WAU as a single rolling 12-week chart. ROI as a single quarterly time-savings estimate with the methodology footnoted. That's it. If you can't fit AI adoption on one slide for the board, your dashboard is too cluttered and you're hiding from the numbers.",
      "The hardest measurement question is what to do with the error-flag rate. Most organizations don't have one because they haven't built the flag mechanism into their workflow. The simplest implementation is a one-click 'this was wrong' button on every AI output, surfaced in the dashboard. The number itself is less important than the trend; if it's flat, your prompts and use cases are stable. If it's rising, something has degraded.",
      "Measurement is non-negotiable not because it's intellectually satisfying but because it's politically necessary. AI programs that can't show numbers get cut in the next budget cycle. AI programs that can show numbers get expanded.",
    ],
  },
  "fractional-caio": {
    paragraphs: [
      "The fractional Chief AI Officer role exists because most SMBs can't justify a full-time hire at $300–500k all-in, but desperately need the decisions made. Same pattern as fractional CFO: you don't need a full-time financial leader at 50 employees, but you absolutely need someone who can answer the questions a CFO answers.",
      "A typical engagement is 20–40 hours per month at the C-table. Functional membership on the executive leadership team. Quarterly board reports. Annual AI roadmap with OKRs. Vendor management. Policy ownership. Champion network leadership. External relationships with the AI infrastructure providers (Anthropic, OpenAI, AWS, Microsoft) maintained on the organization's behalf.",
      "The role works when AI is genuinely strategic to the organization but the CEO and COO are over-stretched. It doesn't work when the org just wants someone to nod at decisions the CEO has already made — that's a board observer, not a CAIO.",
      "The most common confusion is the difference between a CAIO and an implementation consultant. The implementation consultant ships specific deployments. The CAIO sets strategy, signs vendor contracts, presents to the board, and decides the calendar of which deployments happen when. The two roles complement; sometimes they're the same person at different points in the engagement.",
      "Pricing typically runs $10–20k per month with a 12-month minimum. The minimum matters because the role's value is in the relationship and the decisions, both of which take a quarter to start producing. A 3-month fractional CAIO arrangement is almost always too short to be useful.",
      "The exit pattern is one of three things. The org outgrows fractional and recruits a full-time CAIO (placement fee paid; relationship preserved). The org's AI strategy stabilizes to the point where a governance retainer is sufficient (downshift, not exit). Or the org and the fractional CAIO discover they're not a fit and the contract isn't renewed (uncommon but it happens).",
      "The role is rare because the credential is rare. Full-time CAIOs in 2026 are mostly people who've shipped specific large AI programs and want to do it again. There aren't many of them, and most are recruited away to enterprise roles before they consider fractional work. The fractional CAIOs who exist tend to come from operator backgrounds (CHRO, COO, CFO) with a documented AI deployment in their portfolio.",
    ],
  },
  "operator-vs-consultant": {
    paragraphs: [
      "Most AI consulting firms have the same structural problem: their senior people stopped operating five or more years ago. Their advice is theoretical. They've never had to convince a skeptical clinician, defuse a compliance officer's veto, or look a frontline staff member in the eye and explain why a new tool is worth their attention.",
      "What the consultant says: 'You'll need a change management workstream.' What the operator says: 'In week three, the lead nurse is going to ask you why this is different from the last initiative that promised time savings and didn't deliver. Here's the answer she'll accept.'",
      "The operator answer is harder to come by because it requires having been in the chair. You can't read about week three; you have to live week three. And the difference shows up in the deployment in ways that are hard to articulate but easy to see — the operator-led program has staff buy-in by month two; the consultant-led program is still presenting steering committee updates in month four.",
      "I'm an operator who consults. The credibility is sitting in the chair while the engagement is running. The 83% adoption number isn't case-study material I dust off in pitch meetings — it's the daily work, ongoing, with the next quarterly leadership update due next week. Every recommendation I make to a client is being stress-tested against my own ongoing program at the same time.",
      "This will eventually change. The practice will outgrow concurrent operating, or the operating role will end, or both. But for now the dual posture is a feature, not a constraint. Every client engagement informs the operating role; every operating decision informs the engagements. The credibility compounds.",
    ],
  },
};
